Vacation Flask/src/views/about_view.py
from flask import render_template, Blueprint

# Managing the entire view
about_blueprint = Blueprint("about_view", __name__)

@about_blueprint.route("/about")
def about():
    return render_template("about_us.html", active = "about")

Vacation Flask/src/views/auth_view.py
from flask import render_template, Blueprint, redirect, request, url_for
from facades.auth_facade import AuthFacade
from models.client_errors import ValidationError, AuthError

# Managing the entire view
auth_blueprint = Blueprint("auth_view", __name__)

# Create auth facade: 
auth_facade = AuthFacade()

# Register new user:
@auth_blueprint.route("/register", methods = ["GET", "POST"])
def register():
    try:
        if request.method == "GET":
            return render_template("register.html", new_user = {})
        auth_facade.register() 
        return redirect(url_for("vacations_view.vacations"))
    except ValidationError as err: # Check the validation error
           return render_template("register.html", error = err.message, new_user = err.model)
       
    # Register new user:
@auth_blueprint.route("/login", methods = ["GET", "POST"])   
def login():
    try:
        if request.method == "GET":
            err = request.args.get("error") 
            return render_template("login.html", error = err, credentials = {})
        auth_facade.login()
        return redirect(url_for("vacations_view.vacations"))
    except(ValidationError, AuthError) as err:
        return render_template("login.html", error = err.message, credentials=err.model)  
        
@auth_blueprint.route("/logout")
def logout():
    auth_facade.logout()
    return redirect(url_for("home_view.home"))  

Vacation Flask/src/views/home_view.py
from flask import render_template, Blueprint

# Managing the entire view
home_blueprint = Blueprint("home_view", __name__)

@home_blueprint.route("/")
@home_blueprint.route("/home")
def home():
    return render_template("home.html", active = "home")

Vacation Flask/src/views/join_us_view.py
from flask import render_template, Blueprint

# Managing the entire view
join_us_blueprint = Blueprint("join_us_view", __name__)

@join_us_blueprint.route("/join_us")
def join_us():
    return render_template("join_us.html", active = "join_us")

Vacation Flask/src/views/reviews_view.py
from flask import render_template, Blueprint

# Managing the entire view
reviews_blueprint = Blueprint("reviews_view", __name__)

@reviews_blueprint.route("/reviews")
def reviews():
    return render_template("reviews.html", active = "reviews")

Vacation Flask/src/views/vacations_view.py
from flask import render_template, Blueprint, send_file
from models.client_errors import ValidationError, AuthError, ResourceNotFoundError
from facades.vacation_facade import VacationFacade
from facades.auth_facade import AuthFacade
from flask import request, redirect, url_for, session
from utils.image_handler import ImageHandler

# Managing the entire view
vacations_blueprint = Blueprint("vacations_view", __name__)

# Create facades:
vacations_facade = VacationFacade()
auth_facade = AuthFacade()

# Get all vacations


@vacations_blueprint.route("/vacations", methods=["GET", "POST"])
def vacations():
    try:
        user = session.get("user")
        auth_facade.block_anonymous()
        vacations = vacations_facade.get_all_vacations()
        likes = vacations_facade.how_many_likes_for_vacation()
        vacation_like_status = vacations_facade.get_vacations_with_like_status(
            user["user_id"])
        if request.method == "GET":
            return render_template("vacations.html", active="vacations", vacations=vacations, likes=likes, vacation_like_status=vacation_like_status)
    except AuthError as err:
        return redirect(url_for("auth_view.login", error=err.message))


# Insert vacation
@vacations_blueprint.route("/insert", methods=["GET", "POST"])
def insert():
    vacation_countries = vacations_facade.get_countries_name()
    try:
        auth_facade.block_non_admin()
        if request.method == "GET":
            return render_template("insert.html", vacation_countries=vacation_countries)
        vacations_facade.add_new_vacation()
        return redirect(url_for("vacations_view.vacations"))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error=err.message))
    except ValidationError as err:
        return render_template("insert.html", error=err.message, vacation=err.model, vacation_countries=vacation_countries)

# Update vacation


@vacations_blueprint.route("/vacations/update/<int:vacation_id>", methods=["GET", "POST"])
def update(vacation_id):
    vacation_countries = vacations_facade.get_countries_name()
    try:
        auth_facade.block_non_admin()
        if request.method == "GET":
            vacation = vacations_facade.get_one_vacation(vacation_id)
            return render_template("update.html", vacation=vacation, vacation_countries=vacation_countries)
        vacations_facade.update_vacation()
        return redirect(url_for("vacations_view.vacations"))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error=err.message))
    except ResourceNotFoundError as err:
        return render_template("404.html", error=err.message)
    except ValidationError as err:
        vacation = vacations_facade.get_one_vacation(vacation_id)
        return render_template("update.html", error=err.message, vacation=vacation, vacation_countries=vacation_countries)


# Delete vacation
@vacations_blueprint.route("/vacations/delete/<int:vacation_id>")
def delete(vacation_id):
    try:
        auth_facade.block_non_admin()
        vacations_facade.delete_vacation(vacation_id)
        return redirect(url_for("vacations_view.vacations"))
    except AuthError as err:
        return redirect(url_for("auth_view.login", error=err.message))


# Add like to vacation
@vacations_blueprint.route("/vacations/like/<int:user_id>/<int:vacation_id>", methods=["POST"])
def add_like(user_id, vacation_id):
    try:
        is_liked = vacations_facade.is_user_already_liked_same_vacation(
            user_id, vacation_id)
        if not is_liked:
            vacations_facade.add_like_for_vacation(user_id, vacation_id)
        else:
            vacations_facade.delete_like_for_vacation(user_id, vacation_id)
        session["is_liked"] = is_liked
        return redirect(url_for("vacations_view.vacations", is_liked=is_liked))
    except ResourceNotFoundError as err:
        return render_template("404.html", error=err.message)

# Return image file:


@vacations_blueprint.route("/images/countries/<string:image_name>")
def get_image(image_name):
    image_path = ImageHandler.get_image_path(image_name)
    # Returns a complete file (an image file with pixels of the image...)
    return send_file(image_path)


# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Get special vacations
@vacations_blueprint.route("/special_vacations")
def special_locations():
    try:
        auth_facade.block_anonymous()
        special_vacation = vacations_facade.special_locations()
        return render_template("special_vacations.html",
                        vacations=special_vacation)
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    
    
# Get culinary vacations
@vacations_blueprint.route("/culinary_vacations")
def culinary_vacations():
    try:
        auth_facade.block_anonymous()
        special_vacation = vacations_facade.culinary_locations()
        return render_template("culinary_vacations.html",
                        vacations=special_vacation)
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    
    
# Get winter vacations
@vacations_blueprint.route("/winter_vacations")
def winter_vacations():
    try:
        auth_facade.block_anonymous()
        special_vacation = vacations_facade.winter_vacations()
        return render_template("winter_vacations.html",
                        vacations=special_vacation)
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    
    
# Get summer vacations
@vacations_blueprint.route("/summer_vacations")
def summer_vacations():
    try:
        auth_facade.block_anonymous()
        special_vacation = vacations_facade.summer_vacations()
        return render_template("summer_vacations.html",
                        vacations=special_vacation)
    except AuthError as err:
        return redirect(url_for("auth_view.login", error = err.message))
    
    

Vacation Flask/src/templates/about_us.html
{% extends "layout.html" %}

{% block title %}
Beautiful Vacations | About Us
{% endblock title %}

{% block main %}
<section class="about-section">
    <p class="home about-title">About Us</p>
    <div class="about-container">
        <p>At Beautiful Vacations, we believe that travel is not just about reaching a destination; it's about the journey itself. That's why we go above and beyond to ensure that every aspect of your trip is meticulously planned and flawlessly executed. From booking accommodations to arranging guided tours and activities, we handle all the details so you can focus on creating unforgettable memories.</p>

        <p>Our team consists of seasoned travelers and industry experts who are passionate about sharing their knowledge and love for travel with our customers. With years of experience in the tourism and hospitality sectors, we have the expertise to turn your travel aspirations into reality. Whether you're a solo adventurer, a couple seeking romance, or a family in search of fun-filled adventures, we have the perfect itinerary for you.</p>

        <p>At the heart of Beautiful Vacations is our commitment to sustainability and responsible tourism. We strive to minimize our environmental impact and support local communities in the destinations we visit. By partnering with eco-friendly accommodations and promoting cultural immersion experiences, we aim to create positive social and environmental change while offering enriching travel experiences.</p>

        <p>Join us on a journey of discovery, exploration, and adventure. Whether you're embarking on your first solo trip, planning a romantic getaway, or organizing a group adventure with friends, Beautiful Vacations is here to make your travel dreams come true. Let us be your guide to the world's most beautiful destinations, and together, let's create memories that will last a lifetime.</p>

    </div>
</section>
{% endblock main %}

Vacation Flask/src/templates/admin_or_user.html
{% set is_liked = session.get("is_liked") %}
    {% if user.role_id == 1 %}
    
    <span>
        <div class="like-form">
            <a class="edit-delete-button" href="{{url_for('vacations_view.update', vacation_id = vacation.vacation_id)}}">Edit</a>
            <a class="edit-delete-button" onclick="confirmDelete()" href="{{url_for('vacations_view.delete', vacation_id = vacation.vacation_id)}}">Delete</a>    
        </div>    
    </span>
    {% elif user.role_id == 2 %}
    
    <form class="like-form" action="{{ url_for('vacations_view.add_like', user_id=user.user_id, vacation_id=vacation.vacation_id) }}" method="POST">
        <button id="like-{{ vacation.vacation_id }}" class="like-button {% if vacation_like_status[vacation.vacation_id] %}liked{% endif %}" type="submit">
            <span id="heart-{{ vacation.vacation_id }}" class="heart-icon">&#x2665;</span> Likes: <span id="like-count-{{ vacation.vacation_id }}">{{ likes[vacation.vacation_id-1]['total_likes'] }}</span>
        </button>
    </form>

    
    
    
    
    
    
    
    
    
    <br><br>
    {%endif%}

Vacation Flask/src/templates/carousel.html
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      
      <div class="carousel-item">
        <img src="{{url_for('static', filename = 'images/israel/falafel.jpg')}}"  alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
      </div>
      <div class="carousel-item active">
        <img src="{{url_for('static', filename = 'images/israel/tel_aviv_jaffa.jpg')}}"  alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
      </div>
      <div class="carousel-item">
        <img src="{{url_for('static', filename = 'images/israel/sun.jpg')}}"  alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
      </div>
      <div class="carousel-item">
        <img src="{{url_for('static', filename = 'images/israel/tel_aviv_jaffa_2.jpg')}}"  alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
      </div>
      <div class="carousel-item">
        <img src="{{url_for('static', filename = 'images/israel/jerusalem.jpg')}}"  alt="...">
        <div class="carousel-caption d-none d-md-block">
        </div>
      </div>
    </div>
 
  </div>
  

Vacation Flask/src/templates/home.html
{% extends "layout.html" %}

{% block title %}
Beautiful Vacations | Home
{% endblock title %}

{% block main %}
<div class="home">
    <div class="home-title">
        <p>Explore New Destinations With Us!</p>
        <p>Take a trip to your favorite destination and</p>
        <p>Discover a whole new world</p>
    </div>
    <div class="home-cards">
        <div class="card" style="width: 18rem;">
            <img src="{{url_for('static', filename ='images/home_images/nature.jpg')}}" class="card-img-top" alt="...">
            <div class="card-body card-red">
                <a class="card-text" href="{{url_for('vacations_view.special_locations')}}">Special Locations</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img src="{{url_for('static',filename ='images/home_images/pasta.jpg')}}" class="card-img-top" alt="...">
            <div class="card-body card-blue">
                <a class="card-text" href="{{url_for('vacations_view.culinary_vacations')}}">Amazing Food</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img src="{{url_for('static',filename ='images/home_images/summer.jpg')}}" class="card-img-top" alt="...">
            <div class="card-body card-red">
                <a class="card-text" href="{{url_for('vacations_view.summer_vacations')}}">Summer Vacations</a>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <img src="{{url_for('static',filename ='images/home_images/winter.jpg')}}" class="card-img-top" alt="...">
            <div class="card-body card-blue">
                <a class="card-text" href="{{url_for('vacations_view.winter_vacations')}}">Winter Vacations</a>
            </div>
        </div>
    </div>


    <div class="recommendations">
        <p>Traveling Recommendations For March: </p>
        <p>Israel</p>
    </div>
    <div>
        {% include "carousel.html" %}
    </div>
    <p class="">March is a fantastic time to visit Israel, as the country emerges from the cooler winter months into the
        warmth of spring. With the weather becoming pleasantly mild and the landscapes lush with blooming flowers, March
        offers an ideal setting for exploring Israel's rich history, diverse culture, and stunning natural beauty. In
        March, visitors can wander through the ancient streets of Jerusalem's Old City, marvel at the iconic sights of
        Tel Aviv, float in the mineral-rich waters of the Dead Sea, and embark on unforgettable journeys to the sacred
        sites of Bethlehem, Nazareth, and the Galilee region. Additionally, March in Israel coincides with several
        significant religious festivals, including Purim, offering travelers a unique opportunity to immerse themselves
        in the country's vibrant traditions and celebrations.</p>
</div>

{% endblock main %}

Vacation Flask/src/templates/join_us.html
{% extends "layout.html" %}

{% block title %}
Beautiful Vacations | Join Us
{% endblock title %}

{% block main %}

<section class="login-page">
    <h2 class="home-title">Join Us</h2>
    <p class="home">Interested in joining our community? Fill out the form below and stay connected with Beautiful Vacations!</p>
    <br>
    <form class="login-form">
        <div class="form-group">
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" required>
        </div>    
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
        </div> 
        <div class="form-group">
            <label for="message">Message:</label>
            <textarea id="message" name="message" rows="5" required></textarea>
        </div>
        <button type="button">Join Us</button>
    </form>
    <br><br>
    <h3 class="home-title">Subscribe for Deals</h3>
    <p class="home">Stay updated with our latest deals and promotions by subscribing below.</p>
    <form class="login-form">
        <div class="form-group">
            <label for="subscribe_email">Email:</label>
            <input type="email" id="subscribe_email" name="subscribe_email" required>
        </div>
        <button type="button">Subscribe</button>
    </form>
</section>
{% endblock main %}

Vacation Flask/src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='styles/style.css')}}">
    <link rel="icon" type="image/x-icon" href="{{url_for('static', filename='icons/vacation_icon.ico')}}">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body>
    <div class="layout">
        <header>{% block header %}
            {% include "navbar.html" %}
            {% endblock header %}</header>
        <aside>
            <a href="{{url_for('home_view.home')}}" {% if active=='home' %} class="active" {% endif %}>Home</a>
            <a href="{{url_for('vacations_view.vacations')}}" {% if active=='vacations' %} class="active" {% endif %}>Our Beautiful Vacations</a>
            <a href="{{url_for('about_view.about')}}" {% if active=='about' %} class="active" {% endif %}>About Us</a>
            <a href="{{url_for('reviews_view.reviews')}}" {% if active=='reviews' %} class="active" {% endif %}>Our Reviews</a>
            <a href="{{url_for('join_us_view.join_us')}}" {% if active=='join_us' %} class="active" {% endif %}>Join Us</a>
            <img class="mickey" src="{{url_for('static',filename ='images/mickey mouse.jpg')}}" alt="">
        </aside>
        <main>
            {% block main %}
            {% endblock main %}
            {% if error %} <span class="error">{{error}}</span> {% endif %}
        </main>
        <footer>
            <div>
            <p>&copy; 2024 Beautiful Vacations. All rights reserved.</p>
        </div>
    </footer>
    </div>
</body>
</html>

Vacation Flask/src/templates/navbar.html
{% set user = session.get("user") %}

<nav class="navbar bg-body-tertiary" data-bs-theme="dark" style="background-color: green;">
    <div class="container-fluid">
      <a class="navbar-brand" >
        <img src="{{url_for('static', filename = 'icons/bv.svg')}}" alt="Logo" width="10" height="10" class="d-inline-block align-text-top">
        <p>Beautiful Vacations</p>
      </a>
      {% if user  %}
      <span class="user-auth">
        Hello {{user.first_name}} {{user.last_name}},
        <a href="{{url_for('auth_view.logout')}}">Logout</a>
      </span>
      
      
      {% else %}
      <div>
        <span class="user-auth">
            Hello Guest,  
            <a href="{{url_for('auth_view.login')}}">Login</a>
            |
            <a href="{{url_for('auth_view.register')}}">Register</a>
        </span>
    </div>
      {% endif %}
    </div>
  </nav>

Vacation Flask/src/templates/register.html
{% extends "layout.html" %}

{% block title %}
Beautiful Vacations | Register
{% endblock title %}

{% block main %}

<div class="login-page">   
    <h1>Register to Beautiful Vacations</h1>
    <form method="post" class="login-form">
        <div class="form-group">
            <label>First name: </label>
            <input type="text" name="first_name" value="{{new_user.first_name}}"  required minlength="2" maxlength="30">
            
        </div>
        <div class="form-group">
            <label>Last name: </label>
            <input type="text" name="last_name" value="{{new_user.last_name}}"  required minlength="2" maxlength="30">
        </div>
        <div class="form-group">
            <label>Email: </label>
            <input type="email" name="email" value="{{new_user.email}}"  required minlength="5" maxlength="100">
        </div>
        <div class="form-group">
            <label>Password: </label>
            <input type="password" name="password" value="{{new_user.password}}"  required minlength="4" maxlength="60">
        </div>
        <button>Sign Up</button>
        
        <div class="member">
            <p>Already a member?</p>
            <a href="{{url_for('auth_view.login')}}">Login</a>
        </div>
    </form>

</div>


<!-- <form method="post" class="fancy-form">

    <label>First name: </label>
    <input type="text" name="first_name" value="{{new_user.first_name}}" class="form-control" required minlength="2" maxlength="30">

    <label>Last name: </label>
    <input type="text" name="last_name" value="{{new_user.last_name}}" class="form-control" required minlength="2" maxlength="30">

    <label>Email: </label>
    <input type="email" name="email" value="{{new_user.email}}" class="form-control" required minlength="5" maxlength="100">

    <label>Password: </label>
    <input type="password" name="password" value="{{new_user.password}}" class="form-control" required minlength="4" maxlength="60">

    <button class="btn btn-primary w-100">Register</button>
    
</form> -->

{% endblock main %}

Vacation Flask/src/templates/special_vacations.html
{% extends "layout.html" %}

{% block title %}
Beautiful Vacations | Special Vacations
{% endblock title %}



{% block main %}
<h2 class="home-title">Destination Delights: Unforgettable Vacations in Unique Locations</h2>
<div class="vacation-card-container">
    {% for vacation in vacations %}
        <div class="card">
            <img src="{{url_for('vacations_view.get_image', image_name = (vacation.vacation_image  if vacation.vacation_image else '---'))}}" alt="">
            <div class="card-details">
                
                <h1 class="home-title">{{vacation.country_name}}</h1>
                <br><br>
                <h5><span>📅 {{vacation.vacation_start_date}} - {{vacation.vacation_end_date}}</span></h5>
                <br><br>
                <p>{{ vacation.description[:847] }}...</p>
                <br><br>
                <button class="price-button">${{ vacation.price }}</button>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock main %}

Vacation Flask/src/templates/summer_vacations.html
{% extends "layout.html" %}

{% block title %}
Beautiful Vacations | Summer Vacations
{% endblock title %}



{% block main %}
<h2 class="home-title">Sun-Kissed Adventures: Summer Escapes to Paradise</h2>
<div class="vacation-card-container">
    {% for vacation in vacations %}
        <div class="card">
            <img src="{{url_for('vacations_view.get_image', image_name = (vacation.vacation_image  if vacation.vacation_image else '---'))}}" alt="">
            <div class="card-details">
                
                <h1 class="home-title">{{vacation.country_name}}</h1>
                <br><br>
                <h5><span>📅 {{vacation.vacation_start_date}} - {{vacation.vacation_end_date}}</span></h5>
                <br><br>
                <p>{{ vacation.description[:847] }}...</p>
                <br><br>
                <button class="price-button">${{ vacation.price }}</button>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock main %}

Vacation Flask/src/templates/update.html
{% extends "layout.html" %}

{% block title %}
Beautiful Vacations | Update Vacation
{% endblock title %}

{% block main %}

<form method="post" class="update-form"  enctype="multipart/form-data">
    <input type="hidden" name="vacation_id" value="{{vacation.vacation_id}}">
    <label>Country:</label>
    <select class="form-control center-select" id="selected_country_id" name="country_id">
        {% for country in vacation_countries %}
          {% if country.country_id == vacation.country_id %}
            <option value="{{ country.country_id }}" selected>{{ country.country_name }}</option>
          {% else %}
            <option value="{{ country.country_id }}">{{ country.country_name }}</option>
          {% endif %}
        {% endfor %}
      </select>
    <br><br>
    <label>Description: </label>
    <textarea name="description" id="" cols="30" rows="10"  required>{{vacation.description}} </textarea>
    <br><br>
    <label>Start on: </label>
    <input type="date" name="vacation_start_date" value="{{vacation.vacation_start_date}}" onchange="validateVacationsDates()" required>
    <br><br>
    <label>End on: </label>
    <input type="date" name="vacation_end_date"  value="{{vacation.vacation_end_date}}"required onchange="validateVacationsDates()">
    <label>Price: </label>
    <div class="price"></div>
        <div class="input-container">
            <input type="number" name="price" value="{{vacation.price}}" required max="9999" min="0" required>
        </div>
    <br>
    <div class="image-container">
        <img src="{{url_for('vacations_view.get_image', image_name = (vacation.vacation_image  if vacation.vacation_image else '---'))}}" alt="">
        <label for="vacation_image" class="upload-label">Change image</label>
        <input type="file" class="form-control-file" id="vacation_image" name="vacation_image"  accept="image/*" >
    </div>    
    <br><br>
    <button class="btn btn-primary w-80">Update Vacation</button>
    <br><br>
    <button class="btn btn-primary w-80">Cancel</button>
</form>

{% endblock main %}

Vacation Flask/src/templates/vacations.html
{% extends "layout.html" %}

{% block title %}
Beautiful Vacations | Our Vacations
{% endblock title %}

{% set user = session.get("user") %}


{% block main %}
<h2 class="home-title">Explore Our Spectacular Vacation Destinations</h2>
{% if user.role_id == 1 %}
    <p class="user-edit">Hello {{user.first_name}}</p>
    <p class="user-edit">Do you want to add vacation?</p>
    <a class="edit-delete-button" href="{{url_for('vacations_view.insert')}}">Add Vacation</a>
    <br><br>
{%endif%}

<div class="vacation-card-container">
    {% for vacation in vacations %}
        <div class="card">
            <img src="{{url_for('vacations_view.get_image', image_name = (vacation.vacation_image  if vacation.vacation_image else '---'))}}" alt="">
            <div class="card-details">
                {% include "admin_or_user.html" %}
                <h1 class="home-title">{{vacation.country_name}}</h1>
                <br><br>
                <h5><span>📅 {{vacation.vacation_start_date}} - {{vacation.vacation_end_date}}</span></h5>
                <br><br>
                <p>{{ vacation.description[:847] }}...</p>
                <br><br>
                <button class="price-button">${{ vacation.price }}</button>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock main %}

Vacation Flask/src/templates/winter_vacations.html
{% extends "layout.html" %}

{% block title %}
Beautiful Vacations | Winter Vacations
{% endblock title %}



{% block main %}
<h2 class="home-title">Frosty Escapes: Winter Wonderland Vacations to Chill and Thrill</h2>
<div class="vacation-card-container">
    {% for vacation in vacations %}
        <div class="card">
            <img src="{{url_for('vacations_view.get_image', image_name = (vacation.vacation_image  if vacation.vacation_image else '---'))}}" alt="">
            <div class="card-details">
                
                <h1 class="home-title">{{vacation.country_name}}</h1>
                <br><br>
                <h5><span>📅 {{vacation.vacation_start_date}} - {{vacation.vacation_end_date}}</span></h5>
                <br><br>
                <p>{{ vacation.description[:847] }}...</p>
                <br><br>
                <button class="price-button">${{ vacation.price }}</button>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock main %}